# action.yml
name: 'Dependencies license compliance checker'
author: 'Vitaly R. Samigullin'
description: 'Detect license names and types for Python PyPI packages or a list of licenses obtained by third-party tools'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  requirements:
    description: 'Path to requirements file(s)'
    required: false
  external:
    description: 'Path to CSV file(s) in format: `package_name,license_name[,...]`'
    required: false
  fail:
    description: 'Return non-zero exit code if specified license type(s) found'
    required: false
  fails-only:
    description: 'Print only packages of license types specified with `fail` input.'
    required: false
  exclude:
    description: 'PCRE to exclude matching packages'
    required: false
  pre:
    description: 'Include pre-release and development versions'
    required: false
  with-totals:
    description: 'Print totals for license types'
    required: false
  totals-only:
    description: 'Print only totals for license types'
    required: false
  table-headers:
    description: 'Print table headers'
    required: false
  no-external-csv-headers:
    description: 'CSV file provided via external input does not contain header line'
    required: false
outputs:
  report:
    description: 'License check report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements }}
    - ${{ inputs.external }}
    - ${{ inputs.fail }}
    - ${{ inputs.fails-only }}
    - ${{ inputs.exclude }}
    - ${{ inputs.pre }}
    - ${{ inputs.with-totals }}
    - ${{ inputs.totals-only }}
    - ${{ inputs.table-headers }}
    - ${{ inputs.no-external-csv-headers }}
